export const PLAYER_FINE_LIST_REQUEST = "PLAYER_FINE_LIST_REQUEST"
export const PLAYER_FINE_LIST_SUCCESS = "PLAYER_FINE_LIST_SUCCESS"
export const PLAYER_FINE_LIST_FAIL = "PLAYER_FINE_LIST_FAIL"

export const PLAYER_DETAILS_REQUEST = "PLAYER_DETAILS_REQUEST"
export const PLAYER_DETAILS_SUCCESS = "PLAYER_DETAILS_SUCCESS"
export const PLAYER_DETAILS_FAIL = "PLAYER_DETAILS_FAIL"

export const PLAYER_LIST_REQUEST = "PLAYER_LIST_REQUEST"
export const PLAYER_LIST_SUCCESS = "PLAYER_LIST_SUCCESS"
export const PLAYER_LIST_FAIL = "PLAYER_LIST_FAIL"

export const PLAYER_CREATE_REQUEST = "PLAYER_CREATE_REQUEST"
export const PLAYER_CREATE_SUCCESS = "PLAYER_CREATE_SUCCESS"
export const PLAYER_CREATE_FAIL = "PLAYER_CREATE_FAIL"

export const PLAYER_UPDATE_REQUEST = "PLAYER_UPDATE_REQUEST"
export const PLAYER_UPDATE_SUCCESS = "PLAYER_UPDATE_SUCCESS"
export const PLAYER_UPDATE_FAIL = "PLAYER_UPDATE_FAIL"

export const PLAYER_DELETE_REQUEST = "PLAYER_DELETE_REQUEST"
export const PLAYER_DELETE_SUCCESS = "PLAYER_DELETE_SUCCESS"
export const PLAYER_DELETE_FAIL = "PLAYER_DELETE_FAIL"

export const FINE_LIST_REQUEST = "FINE_LIST_REQUEST"
export const FINE_LIST_SUCCESS = "FINE_LIST_SUCCESS"
export const FINE_LIST_FAIL = "FINE_LIST_FAIL"

export const FINE_CREATE_REQUEST = "FINE_CREATE_REQUEST"
export const FINE_CREATE_SUCCESS = "FINE_CREATE_SUCCESS"
export const FINE_CREATE_FAIL = "FINE_CREATE_FAIL"

export const FINE_UPDATE_REQUEST = "FINE_UPDATE_REQUEST"
export const FINE_UPDATE_SUCCESS = "FINE_UPDATE_SUCCESS"
export const FINE_UPDATE_FAIL = "FINE_UPDATE_FAIL"

export const FINE_DELETE_REQUEST = "FINE_DELETE_REQUEST"
export const FINE_DELETE_SUCCESS = "FINE_DELETE_SUCCESS"
export const FINE_DELETE_FAIL = "FINE_DELETE_FAIL"