# Generated by Django 4.0 on 2022-02-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
