# Generated by Django 4.0 on 2022-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fine_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
